image: python:latest

stages:
  - makefile-linter
  - sql-linter

Makefile:
  stage: makefile-linter
  script:
    - pip install git+https://github.com/konturio/make-profiler
    - profile_make_lint

SQLLint:
  stage: sql-linter
  script:
    - python3 -m pip install sqlfluff
    - sqlfluff lint -f ./ci/config.sqlfluff .