FROM debian:stable-slim

# install osm2pgsql dependencies
RUN apt-get update \
  && apt-get install -y wget git make cmake g++ libboost-dev libboost-system-dev \
  libboost-filesystem-dev libexpat1-dev zlib1g-dev \
  libbz2-dev libpq-dev libproj-dev lua5.3 liblua5.3-dev pandoc

# build and install osm2pgsql
RUN git clone git://github.com/openstreetmap/osm2pgsql.git \
    && mkdir osm2pgsql/build \
    && cd osm2pgsql/build \
    && cmake .. \
    && make -j$(nproc) \
    && make install

# golang is required to build tile_generator
RUN apt-get install -y golang

# postgresql-client is required to use psql from Makefile
RUN apt-get -y install gnupg2
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update
RUN apt-get -y install postgresql-client-14

# python2 is required to run Kothic
RUN apt-get -y install python2

COPY basemap /basemap
COPY tile_generator /tile_generator
COPY Makefile Makefile

CMD ["make", "data/basemap.mbtiles"]
