drop table if exists bivariate_colors;
create table bivariate_colors (
    color text,
    color_comment text,
    corner json
);

insert into bivariate_colors (color, color_comment, corner)
values ('#58b075', 'green', jsonb_build_array('good')),
       ('#e8e89d', 'yellow', jsonb_build_array('bad', 'unimportant')),
       ('#5d5398', 'purple', jsonb_build_array('bad', 'good')),
       ('#89c89e', 'alternate_color_2_green?', jsonb_build_array('good', 'bad')),
       ('#ada9c8', 'lilac', jsonb_build_array('bad')),
       ('#5ac87f', 'pale green', jsonb_build_array('bad', 'unimportant', 'good')),
       ('#5ac87f', 'pale green', jsonb_build_array('good', 'unimportant')),
       ('#53986a', 'dark green', jsonb_build_array('good', 'important')),
       ('#5ac87f', 'pale green', jsonb_build_array('good', 'bad', 'unimportant')),
       ('#58b075', 'green', jsonb_build_array('good', 'neutral')),
       ('#58b075', 'green', jsonb_build_array('neutral', 'good')),
       ('#e41a1c', 'bloody red', jsonb_build_array('bad', 'important')),
       ('#f37e7e', 'light red', jsonb_build_array('neutral', 'bad')),
       ('#f37e7e', 'light red', jsonb_build_array('neutral', 'bad')),
       ('#f37e7e', 'light red', jsonb_build_array('bad', 'neutral')),
       ('#5ac87f', 'pale green', jsonb_build_array('unimportant', 'good')),
       ('#53986a', 'dark green', jsonb_build_array('important', 'good')),
       ('#f37e7e', 'light red',jsonb_build_array('unimportant', 'bad')),
       ('#e41a1c', 'bloody red', jsonb_build_array('important', 'bad')),
       ('#f37e7e', 'light red', jsonb_build_array('neutral', 'bad', 'unimportant')),
       ('#f37e7e', 'light red', jsonb_build_array('bad', 'unimportant', 'neutral')),
       ('#cccccc', '#cccccc', jsonb_build_array('neutral')),
       ('#c85a5a', 'red', jsonb_build_array('bad', 'unimportant', 'important')),
       ('#999999', 'dark grey', jsonb_build_array('bad', 'important', 'good')),
       ('#e8e89d', 'yellow', jsonb_build_array('good', 'unimportant', 'bad')),
       ('#999999', 'dark grey', jsonb_build_array('good', 'bad', 'important')),
       ('#c85a5a', 'red', jsonb_build_array('important', 'bad', 'unimportant')),
       ('#abd8ed', 'sky blue', jsonb_build_array('neutral', 'unimportant')),
       ('#e8e89d', 'yellow', jsonb_build_array('important', 'neutral')),
       ('#e8e89d', 'yellow', jsonb_build_array('neutral', 'important')),
       ('#999999', 'dark grey', jsonb_build_array('good', 'important', 'bad')),
       ('#abd8ed', 'sky blue', jsonb_build_array('unimportant', 'neutral')),
       ('#e8e89d',  'yellow', jsonb_build_array('bad', 'good', 'unimportant')),
       ('#999999', 'dark grey', jsonb_build_array('bad', 'good', 'important')),
       ('#c85a5a', 'red', jsonb_build_array('bad', 'important', 'unimportant')),
       ('#5ac87f', 'pale green', jsonb_build_array('neutral', 'good', 'unimportant')),
       ('#5ac87f', 'pale green', jsonb_build_array('good', 'unimportant', 'neutral')),
       ('#e41a1c',  'bloody red', jsonb_build_array('bad', 'unimportant', 'good', 'important')),
       ('#53986a', 'dark green', jsonb_build_array('neutral', 'good', 'important')),
       ('#c85ac8', 'alternate_color_1_magenta?', jsonb_build_array('unimportant', 'important')),
       ('#e41a1c', 'bloody red', jsonb_build_array('neutral', 'bad', 'important')),
       ('#53986a', 'dark green', jsonb_build_array('good', 'important', 'neutral')),
       ('#e8e89d', 'yellow', jsonb_build_array('unimportant')),
       ('#999999', 'dark grey', jsonb_build_array('important')),
       ('#e41a1c', 'bloody red', jsonb_build_array('good', 'important', 'bad', 'unimportant')),
       ('#e41a1c', 'bloody red', jsonb_build_array('bad', 'important', 'neutral')),
       ('#5ac8c8', 'alternate_color_2_cyan?', jsonb_build_array('important', 'unimportant')),
       ('#58b075', 'green', jsonb_build_array('good', 'unimportant', 'important')),
       ('#58b075', 'green', jsonb_build_array('good', 'important', 'unimportant')),
       ('#c85a5a', 'red', jsonb_build_array('unimportant', 'bad', 'important')),
       ('#58b075',  'green', jsonb_build_array('important', 'good', 'unimportant')),
       ('#58b075', 'green', jsonb_build_array('unimportant', 'good', 'important')),
       ('#cccccc', '#cccccc', jsonb_build_array('good', 'unimportant', 'bad', 'important')),
       ('#cccccc', '#cccccc', jsonb_build_array('bad', 'important', 'good', 'unimportant'));
