call transform_hasc_to_h3(
    'global_rva_indexes',
    'global_rva_h3',
    'hasc',
    '{raw_mhe_pop_scaled, raw_mhe_cap_scaled, raw_mhe_index, relative_mhe_pop_scaled,
    relative_mhe_cap_scaled, relative_mhe_index, mhe_index, life_expectancy_scale,
    infant_mortality_scale, maternal_mortality_scale, prevalence_undernourished_scale,
    vulnerable_health_status_index, pop_wout_improved_sanitation_scale,
    pop_wout_improved_water_scale, clean_water_access_vulnerability_index,
    adult_illiteracy_scale, gross_enrollment_scale, years_of_schooling_scale,
    pop_wout_internet_scale, info_access_vulnerability_index,
    export_minus_import_percent_scale, average_inflation_scale,
    economic_dependency_scale, economic_constraints_index, female_govt_seats_scale,
    female_male_secondary_enrollment_scale, female_male_labor_ratio_scale,
    gender_inequality_index, max_political_discrimination_scale,
    max_economic_discrimination_scale, ethnic_discrimination_index,
    marginalization_index, population_change_scale, urban_population_change_scale,
    population_pressures_index, freshwater_withdrawals_scale, forest_area_change_scale,
    ruminant_density_scale, environmental_stress_index, recent_disaster_losses_scale,
    recent_disaster_deaths_scale, recent_disaster_impacts_index,
    recent_conflict_deaths_scale, displaced_populations_scale, conflict_impacts_index,
    vulnerability_index, voice_and_accountability_scale, rule_of_law_scale,
    political_stability_scale, govt_effectiveness_scale, control_of_corruption_scale,
    governance_index, gni_per_capita_scale, reserves_per_capita_scale,
    economic_capacity_index, fixed_phone_access_scale, mobile_phone_access_scale,
    internet_server_access_scale, communications_capacity_index,
    port_rnwy_density_scale, road_rr_density_scale, transportation_index,
    hospital_bed_density_scale, nurses_midwives_scale, physicians_scale,
    health_care_capacity_index, infrastructure_capacity_index, biome_protection_scale,
    marine_protected_area_scale, environmental_capacity_index, coping_capacity_index,
    resilience_index, mhr_index}'::text[],
    8
);
call generate_overviews(
    'global_rva_h3',
    '{raw_mhe_pop_scaled, raw_mhe_cap_scaled, raw_mhe_index, relative_mhe_pop_scaled,
    relative_mhe_cap_scaled, relative_mhe_index, mhe_index, life_expectancy_scale,
    infant_mortality_scale, maternal_mortality_scale, prevalence_undernourished_scale,
    vulnerable_health_status_index, pop_wout_improved_sanitation_scale,
    pop_wout_improved_water_scale, clean_water_access_vulnerability_index,
    adult_illiteracy_scale, gross_enrollment_scale, years_of_schooling_scale,
    pop_wout_internet_scale, info_access_vulnerability_index,
    export_minus_import_percent_scale, average_inflation_scale,
    economic_dependency_scale, economic_constraints_index, female_govt_seats_scale,
    female_male_secondary_enrollment_scale, female_male_labor_ratio_scale,
    gender_inequality_index, max_political_discrimination_scale,
    max_economic_discrimination_scale, ethnic_discrimination_index,
    marginalization_index, population_change_scale, urban_population_change_scale,
    population_pressures_index, freshwater_withdrawals_scale, forest_area_change_scale,
    ruminant_density_scale, environmental_stress_index, recent_disaster_losses_scale,
    recent_disaster_deaths_scale, recent_disaster_impacts_index,
    recent_conflict_deaths_scale, displaced_populations_scale, conflict_impacts_index,
    vulnerability_index, voice_and_accountability_scale, rule_of_law_scale,
    political_stability_scale, govt_effectiveness_scale, control_of_corruption_scale,
    governance_index, gni_per_capita_scale, reserves_per_capita_scale,
    economic_capacity_index, fixed_phone_access_scale, mobile_phone_access_scale,
    internet_server_access_scale, communications_capacity_index,
    port_rnwy_density_scale, road_rr_density_scale, transportation_index,
    hospital_bed_density_scale, nurses_midwives_scale, physicians_scale,
    health_care_capacity_index, infrastructure_capacity_index, biome_protection_scale,
    marine_protected_area_scale, environmental_capacity_index, coping_capacity_index,
    resilience_index, mhr_index}'::text[],
    '{avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,
    avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,
    avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,
    avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg,avg}'::text[],
    8
);
