-- Create h3 coverage from gloval rva statistics using kontur boundaries
-- Using 6th resolution as initial to obtain adequate averages at 4th (basic) on borders
drop table if exists global_rva_data_h3_in;
create table global_rva_data_h3_in as
	select h3_polygon_to_cells(st_subdivide(kb.geom), 6) h3,
	       rva.raw_mhe_pop_exposure,
	       rva.raw_mhe_cap_exp,
	       rva.relative_mhe_pop,
	       rva.relative_mhe_cap,
	       rva.life_expectancy,
	       rva.infant_mortality,
	       rva.maternal_mortality,
	       rva.undernourished,
	       rva.improved_sanitation,
	       rva.improved_water,
	       rva.adult_literacy,
	       rva.gross_enrollment,
	       rva.mean_years_schooling,
	       rva.internet_users_per_100,
	       rva.export_minus_import_percent,
	       rva.five_year_average_inflation,
	       rva.age_dependency_ratio,
	       rva.proportion_female_seats_parliament,
	       rva.fem_to_male_secondary_enroll,
	       rva.fem_to_male_labor,
	       rva.max_political_discrimination,
	       rva.max_economic_discrimination,
	       rva.avg_ann_pop_change,
	       rva.avg_ann_urban_pop_change,
	       rva.freshwater_withdrawal,
	       rva.pct_forest_change,
	       rva.ruminant_density,
	       rva.losses_percent_gni,
	       rva.disaster_deaths_per_10k,
	       rva.conflict_deaths_per_million,
	       rva.refugees,
	       rva.voice_and_accountability,
	       rva.rule_of_law,
	       rva.political_stability,
	       rva.government_effectiveness,
	       rva.control_of_corruption,
	       rva.gni_per_capita,
	       rva.reserves_per_capita,
	       rva.fixed_telephone_per_100,
	       rva.mobile_phone_subs_per_100,
	       rva.secure_internet_servers,
	       rva.hospital_bed_per_10k,
	       rva.nurse_midwife_per_10k,
	       rva.physician_per_10k,
	       rva.avg_biome_protection,
	       rva.marine_protected_area
    from kontur_boundaries kb
        join global_rva_data rva
            on kb.hasc_wiki = rva.hasc;

-- scale to 4th resolution with calculating averages on borders
drop table if exists global_rva_data_h3;
create table global_rva_data_h3 as
	select h3_cell_to_parent(h3, 4) as h3,
	       avg(raw_mhe_pop_exposure) as raw_mhe_pop_exposure,
	       avg(raw_mhe_cap_exp) as raw_mhe_cap_exp,
	       avg(relative_mhe_pop) as relative_mhe_pop,
	       avg(relative_mhe_cap) as relative_mhe_cap,
	       avg(life_expectancy) as life_expectancy,
	       avg(infant_mortality) as infant_mortality,
	       avg(maternal_mortality) as maternal_mortality,
	       avg(undernourished) as undernourished,
	       avg(improved_sanitation) as improved_sanitation,
	       avg(improved_water) as improved_water,
	       avg(adult_literacy) as adult_literacy,
	       avg(gross_enrollment) as gross_enrollment,
	       avg(mean_years_schooling) as mean_years_schooling,
	       avg(internet_users_per_100) as internet_users_per_100,
	       avg(export_minus_import_percent) as export_minus_import_percent,
	       avg(five_year_average_inflation) as five_year_average_inflation,
	       avg(age_dependency_ratio) as age_dependency_ratio,
	       avg(proportion_female_seats_parliament) as proportion_female_seats_parliament,
	       avg(fem_to_male_secondary_enroll) as fem_to_male_secondary_enroll,
	       avg(fem_to_male_labor) as fem_to_male_labor,
	       avg(max_political_discrimination) as max_political_discrimination,
	       avg(max_economic_discrimination) as max_economic_discrimination,
	       avg(avg_ann_pop_change) as avg_ann_pop_change,
	       avg(avg_ann_urban_pop_change) as avg_ann_urban_pop_change,
	       avg(freshwater_withdrawal) as freshwater_withdrawal,
	       avg(pct_forest_change) as pct_forest_change,
	       avg(ruminant_density) as ruminant_density,
	       avg(losses_percent_gni) as 0losses_percent_gni,
	       avg(disaster_deaths_per_10k) as disaster_deaths_per_10k,
	       avg(conflict_deaths_per_million) as conflict_deaths_per_million,
	       avg(refugees) as refugees,
	       avg(voice_and_accountability) as voice_and_accountability,
	       avg(rule_of_law) as rule_of_law,
	       avg(political_stability) as political_stability,
	       avg(government_effectiveness) as government_effectiveness,
	       avg(control_of_corruption) as control_of_corruption,
	       avg(gni_per_capita) as gni_per_capita,
	       avg(reserves_per_capita) as reserves_per_capita,
	       avg(fixed_telephone_per_100) as fixed_telephone_per_100,
	       avg(mobile_phone_subs_per_100) as mobile_phone_subs_per_100,
	       avg(secure_internet_servers) as secure_internet_servers,
	       avg(hospital_bed_per_10k) as hospital_bed_per_10k,
	       avg(nurse_midwife_per_10k) as nurse_midwife_per_10k,
	       avg(physician_per_10k) as physician_per_10k,
	       avg(avg_biome_protection) as avg_biome_protection,
	       avg(marine_protected_area) as marine_protected_area,
		   4 as resolution
    from global_rva_data_h3_in
    group by 1;

-- drop temporary table
drop table if exists global_rva_data_h3_in;