drop table if exists stat_h3_quality;
create table stat_h3_quality as (
    select *
    from
        (
            select
                h3_to_parent(a.h3) as h3_parent,
                avg(a.count) as agg_count,
                avg(a.count_6_months) as agg_count_6_months,
                avg(a.building_count) as agg_building_count,
                avg(a.building_count_6_months) as agg_building_count_6_months,
                avg(a.highway_length) as agg_highway_length,
                avg(a.highway_length_6_months) as agg_highway_length_6_months,
                avg(a.osm_users) as agg_osm_users,
                avg(a.population) as agg_population,
                avg(a.residential) as agg_residential,
                avg(a.gdp) as agg_gdp,
                avg(a.min_ts) as agg_min_ts,
                avg(a.max_ts) as agg_max_ts,
                avg(a.avgmax_ts) as agg_avgmax_ts,
                avg(a.local_hours) as agg_local_hours,
                avg(a.total_hours) as agg_total_hours,
                avg(a.view_count) as agg_view_count,
                avg(a.area_km2) as agg_area_km2,
                avg(a.populated_area_km2) as agg_populated_area_km2,
                avg(a.one) as agg_one,
                avg(a.total_building_count) as agg_total_building_count,
                avg(a.wildfires) as agg_wildfires,
                avg(a.covid19_vaccines) as agg_covid19_vaccines,
                avg(a.avg_slope_gebco_2022) as agg_avg_slope_gebco_2022,
                avg(a.avg_elevation_gebco_2022) as agg_avg_elevation_gebco_2022,
                avg(a.forest) as agg_forest,
                avg(a.avg_ndvi) as agg_avg_ndvi,
                avg(a.covid19_confirmed) as agg_covid19_confirmed,
                avg(a.population_prev) as agg_population_prev,
                avg(a.industrial_area) as agg_industrial_area,
                avg(a.volcanos_count) as agg_volcanos_count,
                avg(a.pop_under_5_total) as agg_pop_under_5_total,
                avg(a.pop_over_65_total) as agg_pop_over_65_total,
                avg(a.poverty_families_total) as agg_poverty_families_total,
                avg(a.pop_disability_total) as agg_pop_disability_total,
                avg(a.pop_not_well_eng_speak) as agg_pop_not_well_eng_speak,
                avg(a.pop_without_car) as agg_pop_without_car,
                avg(a.evergreen_needle_leaved_forest) as agg_evergreen_needle_leaved_forest,
                avg(a.shrubs) as agg_shrubs,
                avg(a.herbage) as agg_herbage,
                avg(a.unknown_forest) as agg_unknown_forest,
                avg(a.days_maxtemp_over_32c_1c) as agg_days_maxtemp_over_32c_1c,
                avg(a.days_maxtemp_over_32c_2c) as agg_days_maxtemp_over_32c_2c,
                avg(a.days_mintemp_above_25c_1c) as agg_days_mintemp_above_25c_1c,
                avg(a.days_mintemp_above_25c_2c) as agg_days_mintemp_above_25c_2c,
                avg(a.days_maxwetbulb_over_32c_1c) as agg_days_maxwetbulb_over_32c_1c,
                avg(a.days_maxwetbulb_over_32c_2c) as agg_days_maxwetbulb_over_32c_2c,
                avg(a.mandays_maxtemp_over_32c_1c) as agg_mandays_maxtemp_over_32c_1c,
                avg(a.man_distance_to_fire_brigade) as agg_man_distance_to_fire_brigade,
                avg(a.man_distance_to_hospital) as agg_man_distance_to_hospital,
                avg(a.total_road_length) as agg_total_road_length,
                avg(a.foursquare_places_count) as agg_foursquare_places_count,
                avg(a.foursquare_visits_count) as agg_foursquare_visits_count,
                avg(a.view_count_bf2402) as agg_view_count_bf2402,
                avg(a.mhr_index) as agg_mhr_index,
                avg(a.mhe_index) as agg_mhe_index,
                avg(a.resilience_index) as agg_resilience_index,
                avg(a.coping_capacity_index) as agg_coping_capacity_index,
                avg(a.vulnerability_index) as agg_vulnerability_index,
                avg(a.hazardous_days_count) as agg_hazardous_days_count,
                avg(a.earthquake_days_count) as agg_earthquake_days_count,
                avg(a.drought_days_count) as agg_drought_days_count,
                avg(a.cyclone_days_count) as agg_cyclone_days_count,
                avg(a.wildfire_days_count) as agg_wildfire_days_count,
                avg(a.volcano_days_count) as agg_volcano_days_count,
                avg(a.flood_days_count) as agg_flood_days_count,
                avg(a.powerlines::float) as agg_powerlines,
                avg(a.night_lights_intensity::float) as agg_night_lights_intensity,
                avg(a.eatery_count::float) as agg_eatery_count,
                avg(a.food_shops_count::float) as agg_food_shops_count,
                avg(a.mapswipe_area_km2::float) as agg_mapswipe_area,
                avg(a.gsa_ghi::float) as agg_gsa_ghi
                --avg(a.gsa_gti::float) as agg_gsa_gti,
                --avg(a.gsa_pvout::float) as agg_gsa_pvout
            from
                stat_h3 a
            where
                a.resolution between 1 and 6
            group by 1 ) a
    join stat_h3 b on a.h3_parent = b.h3
);

