drop table if exists stat_h3_prod;
create table stat_h3_prod  as (
    select a.h3,
           a.zoom,
           a.population,
           a.area_km2,
           a.view_count,
           a.count,
           a.one,
           a.populated_area_km2,
           a.building_count,
           a.highway_length,
           a.total_road_length,
           a.local_hours,
           a.total_hours,
           a.resolution,
           a.avgmax_ts,
           a.man_distance_to_fire_brigade,
           a.view_count_bf2402,
           a.days_mintemp_above_25c_1c,
           a.total_building_count,
           a.count_6_months,
           a.building_count_6_months,
           a.highway_length_6_months,
           a.osm_users,
           a.residential,
           a.gdp,
           a.min_ts,
           a.max_ts,
           a.wildfires,
           --a.covid19_vaccines,
           a.covid19_confirmed,
           a.population_prev,
           a.industrial_area,
           a.volcanos_count,
           a.pop_under_5_total,
           a.pop_over_65_total,
           a.poverty_families_total,
           a.pop_disability_total,
           a.pop_not_well_eng_speak,
           a.pop_without_car,
           a.man_distance_to_hospital,
           a.man_distance_to_bomb_shelters,
           a.man_distance_to_charging_stations,
           a.eatery_count,
           a.food_shops_count,
           a.waste_basket_coverage_area_km2,
           a.solar_farms_placement_suitability,
           a.stddev_accel,
           a.mapswipe_area_km2,
           a.avg_slope_gebco_2022,
           a.avg_elevation_gebco_2022,
           a.forest,
           a.evergreen_needle_leaved_forest,
           a.shrubs,
           a.herbage,
           a.unknown_forest,
           a.cropland,
           a.wetland,
           a.moss_lichen,
           a.bare_vegetation,
           a.builtup,
           a.snow_ice,
           a.permanent_water,
           a.avg_ndvi,
           a.days_maxtemp_over_32c_1c,
           a.days_maxtemp_over_32c_2c,
           a.days_mintemp_above_25c_2c,
           a.days_maxwetbulb_over_32c_1c,
           a.days_maxwetbulb_over_32c_2c,
           a.mandays_maxtemp_over_32c_1c,
           a.hazardous_days_count,
           a.earthquake_days_count,
           a.wildfire_days_count,
           a.drought_days_count,
           a.cyclone_days_count,
           a.volcano_days_count,
           a.flood_days_count,
           a.powerlines,
           a.night_lights_intensity,
           a.gsa_ghi,
           a.worldclim_avg_temperature,
           a.worldclim_min_temperature,
           a.worldclim_max_temperature,
           a.worldclim_amp_temperature,
           a.powerlines_proximity_m,
           a.populated_areas_proximity_m,
           a.power_substations_proximity_m,
           a.solar_power_plants,
           a.safety_index,
           a.geom
    from stat_h3 a;
    
vacuum analyze stat_h3_prod;

create index on stat_h3 using gist (geom, zoom);
-- cannot create index with more than 32 columns, so create more indexes
create index stat_h3_prod_brin_pt1 on stat_h3 using brin (
                                                     area_km2, populated_area_km2, population, count, building_count,
                                                     highway_length, resolution, zoom, geom, one, total_building_count,
                                                     max_ts, total_hours, avgmax_ts, forest,
                                                     evergreen_needle_leaved_forest, shrubs, herbage, unknown_forest,
                                                     min_ts, residential, view_count, count_6_months, total_road_length,
                                                     view_count_bf2402, mhr_index, mhe_index, resilience_index, 
                                                     coping_capacity_index, vulnerability_index, night_lights_intensity
    );

create index stat_h3_prod_brin_pt2 on stat_h3 using brin (
                                                     gdp, highway_length_6_months, wildfires, avg_ndvi,building_count_6_months,
                                                     local_hours, osm_users, covid19_confirmed, population_prev,
                                                     industrial_area, volcanos_count, pop_under_5_total,
                                                     pop_over_65_total, poverty_families_total, pop_disability_total,
                                                     pop_not_well_eng_speak, pop_without_car, mandays_maxtemp_over_32c_1c,
                                                     days_maxtemp_over_32c_1c, days_maxtemp_over_32c_2c,
                                                     days_mintemp_above_25c_1c, days_mintemp_above_25c_2c,
                                                     days_maxwetbulb_over_32c_1c, days_maxwetbulb_over_32c_2c,
                                                     man_distance_to_fire_brigade, man_distance_to_hospital, flood_days_count,
                                                     powerlines, stddev_accel
    );

create index stat_h3_prod_brin_pt3 on stat_h3 using brin (
                                                     eatery_count, food_shops_count, avg_elevation_gebco_2022,
                                                     avg_slope_gebco_2022, mapswipe_area_km2, gsa_ghi,
                                                     worldclim_avg_temperature, worldclim_min_temperature,
                                                     worldclim_max_temperature, worldclim_amp_temperature,
                                                     man_distance_to_bomb_shelters, man_distance_to_charging_stations,
                                                     powerlines_proximity_m, waste_basket_coverage_area_km2,
                                                     populated_areas_proximity_m, power_substations_proximity_m,
                                                     solar_farms_placement_suitability, solar_power_plants,
                                                     safety_index, cropland, wetland, moss_lichen, bare_vegetation, 
                                                     builtup, snow_ice, permanent_water
    );