drop table if exists stat_h3_quality;
create table stat_h3_quality as (
    select *
    from
        (
            select
                h3_cell_to_parent(a.h3) as h3_parent,
                avg(a.count) as agg_count,
                avg(a.count_6_months) as agg_count_6_months,
                avg(a.building_count) as agg_building_count,
                avg(a.building_count_6_months) as agg_building_count_6_months,
                avg(a.highway_length) as agg_highway_length,
                avg(a.highway_length_6_months) as agg_highway_length_6_months,
                avg(a.osm_users) as agg_osm_users,
                avg(a.population) as agg_population,
                avg(a.residential) as agg_residential,
                avg(a.gdp) as agg_gdp,
                avg(a.min_ts) as agg_min_ts,
                avg(a.max_ts) as agg_max_ts,
                avg(a.avgmax_ts) as agg_avgmax_ts,
                avg(a.local_hours) as agg_local_hours,
                avg(a.total_hours) as agg_total_hours,
                avg(a.view_count) as agg_view_count,
                avg(a.area_km2) as agg_area_km2,
                avg(a.populated_area_km2) as agg_populated_area_km2,
                avg(a.one) as agg_one,
                avg(a.total_building_count) as agg_total_building_count,
                avg(a.wildfires) as agg_wildfires,
                avg(a.avg_slope_gebco_2022) as agg_avg_slope_gebco_2022,
                avg(a.avg_elevation_gebco_2022) as agg_avg_elevation_gebco_2022,
                avg(a.forest) as agg_forest,
                avg(a.avg_ndvi) as agg_avg_ndvi,
                avg(a.covid19_confirmed) as agg_covid19_confirmed,
                avg(a.population_prev) as agg_population_prev,
                avg(a.industrial_area) as agg_industrial_area,
                avg(a.volcanos_count) as agg_volcanos_count,
                avg(a.pop_under_5_total) as agg_pop_under_5_total,
                avg(a.pop_over_65_total) as agg_pop_over_65_total,
                avg(a.poverty_families_total) as agg_poverty_families_total,
                avg(a.pop_disability_total) as agg_pop_disability_total,
                avg(a.pop_not_well_eng_speak) as agg_pop_not_well_eng_speak,
                avg(a.pop_without_car) as agg_pop_without_car,
                avg(a.evergreen_needle_leaved_forest) as agg_evergreen_needle_leaved_forest,
                avg(a.shrubs) as agg_shrubs,
                avg(a.herbage) as agg_herbage,
                avg(a.unknown_forest) as agg_unknown_forest,
                avg(a.cropland) as agg_cropland,
                avg(a.wetland) as agg_wetland ,
                avg(a.moss_lichen) as agg_moss_lichen,
                avg(a.bare_vegetation) as agg_bare_vegetation,
                avg(a.builtup) as agg_builtup,
                avg(a.snow_ice) as agg_snow_ice,
                avg(a.permanent_water) as agg_permanent_water,
                avg(a.days_maxtemp_over_32c_1c) as agg_days_maxtemp_over_32c_1c,
                avg(a.days_maxtemp_over_32c_2c) as agg_days_maxtemp_over_32c_2c,
                avg(a.days_mintemp_above_25c_1c) as agg_days_mintemp_above_25c_1c,
                avg(a.days_mintemp_above_25c_2c) as agg_days_mintemp_above_25c_2c,
                avg(a.days_maxwetbulb_over_32c_1c) as agg_days_maxwetbulb_over_32c_1c,
                avg(a.days_maxwetbulb_over_32c_2c) as agg_days_maxwetbulb_over_32c_2c,
                avg(a.mandays_maxtemp_over_32c_1c) as agg_mandays_maxtemp_over_32c_1c,
                avg(a.man_distance_to_fire_brigade) as agg_man_distance_to_fire_brigade,
                avg(a.man_distance_to_hospital) as agg_man_distance_to_hospital,
                avg(a.total_road_length) as agg_total_road_length,
                avg(a.view_count_bf2402) as agg_view_count_bf2402,
                avg(a.hazardous_days_count) as agg_hazardous_days_count,
                avg(a.earthquake_days_count) as agg_earthquake_days_count,
                avg(a.drought_days_count) as agg_drought_days_count,
                avg(a.cyclone_days_count) as agg_cyclone_days_count,
                avg(a.wildfire_days_count) as agg_wildfire_days_count,
                avg(a.volcano_days_count) as agg_volcano_days_count,
                avg(a.flood_days_count) as agg_flood_days_count,
                avg(a.powerlines::float) as agg_powerlines,
                avg(a.night_lights_intensity::float) as agg_night_lights_intensity,
                avg(a.eatery_count::float) as agg_eatery_count,
                avg(a.food_shops_count::float) as agg_food_shops_count,
                avg(a.mapswipe_area_km2::float) as agg_mapswipe_area_km2,
                avg(a.gsa_ghi::float) as agg_gsa_ghi,
                avg(a.worldclim_avg_temperature::float) as agg_worldclim_avg_temperature,
                avg(a.worldclim_min_temperature::float) as agg_worldclim_min_temperature,
                avg(a.worldclim_max_temperature::float) as agg_worldclim_max_temperature,
                avg(a.worldclim_amp_temperature::float) as agg_worldclim_amp_temperature,
                avg(a.man_distance_to_bomb_shelters) as agg_man_distance_to_bomb_shelters,
                avg(a.man_distance_to_charging_stations) as agg_man_distance_to_charging_stations,
                avg(a.powerlines_proximity_m::float) as agg_powerlines_proximity_m,
                avg(a.waste_basket_coverage_area_km2) as agg_waste_basket_coverage_area_km2,
                avg(a.populated_areas_proximity_m::float) as agg_populated_areas_proximity_m,
                avg(a.power_substations_proximity_m::float) as agg_power_substations_proximity_m,
                avg(a.solar_farms_placement_suitability::float) as agg_solar_farms_placement_suitability,
                avg(a.solar_power_plants::float) as agg_solar_power_plants,
                avg(a.safety_index::float) as agg_safety_index,                
                avg(a.stddev_accel) as agg_stddev_accel,
                avg(a.avg_forest_canopy_height::float) as agg_avg_forest_canopy_height,
                avg(a.max_forest_canopy_height::float) as agg_max_forest_canopy_height,
                avg(a.worldbank_total_tax_2019::float) as agg_worldbank_total_tax_2019,
                avg(a.years_to_naturalisation) as agg_years_to_naturalisation,
                avg(a.multiple_citizenship) as agg_multiple_citizenship,
                avg(a.ghs_max_building_height::float) as agg_ghs_max_building_height, 
                avg(a.ghs_avg_building_height::float) as agg_ghs_avg_building_height,
                avg(a.max_osm_building_levels) as agg_max_osm_building_levels, 
                avg(a.avg_osm_building_levels) as agg_avg_osm_building_levels,
                avg(a.osm_hotels_count) as agg_osm_hotels_count,
                avg(a.max_osm_hotels_assesment) as agg_max_osm_hotels_assesment,
                avg(a.avg_osm_hotels_assesment::float) as agg_avg_osm_hotels_assesment,
                avg(a.oam_coverage_area) as agg_oam_coverage_area,
                avg(a.osm_historical_sites_and_museums_count) as agg_osm_historical_sites_and_museums_count,
                avg(a.osm_art_venues_count) as agg_osm_art_venues_count,
                avg(a.osm_entertainment_venues_count) as agg_osm_entertainment_venues_count,
                avg(a.osm_cultural_and_comunity_centers_count) as agg_osm_cultural_and_comunity_centers_count,
                avg(a.oam_number_of_pixels) as agg_oam_number_of_pixels,
                avg(a.worldbank_inflation) as agg_worldbank_inflation,
                avg(a.osm_pharmacy_count) as agg_osm_pharmacy_count,
                avg(a.conflict_stock_displacement) as agg_conflict_stock_displacement,
                avg(a.disaster_stock_displacement) as agg_disaster_stock_displacement,
                avg(a.conflict_internal_displacements) as agg_conflict_internal_displacements,
                avg(a.disaster_internal_displacements) as agg_disaster_internal_displacements,
                avg(a.hdi_2022) as agg_hdi_2022
            from
                stat_h3 a
            where
                a.resolution between 1 and 6
            group by 1 ) a
    join stat_h3 b on a.h3_parent = b.h3
);
