set enable_hashagg = off;
drop table if exists stat_h3_in;
create table stat_h3_in  as (
    select h3,
           resolution,
           resolution as zoom,
           coalesce(sum(count), 0) as count,
           coalesce(sum(count_6_months), 0) as count_6_months,
           coalesce(sum(building_count), 0) as building_count,
           coalesce(sum(building_count_6_months), 0) as building_count_6_months,
           coalesce(sum(total_building_count), 0) as total_building_count,
           coalesce(sum(highway_length), 0) as highway_length,
           coalesce(sum(highway_length_6_months), 0) as highway_length_6_months,
           coalesce(sum(osm_users), 0) as osm_users,
           coalesce(sum(population), 0) as population,
           coalesce(sum(residential), 0) as residential,
           coalesce(sum(gdp), 0) as gdp,
           max(min_ts) as min_ts,
           max(max_ts) as max_ts,
           avg(avgmax_ts) as avgmax_ts,
           coalesce(sum(local_hours), 0) as local_hours,
           coalesce(sum(total_hours), 0) as total_hours,
           coalesce(sum(view_count), 0) as view_count,
           coalesce(sum(wildfires), 0) as wildfires,
           coalesce(sum(covid19_confirmed), 0) as covid19_confirmed,
           coalesce(sum(population_prev), 0) as population_prev,
           coalesce(sum(industrial_area), 0) as industrial_area,
           coalesce(sum(volcanos_count), 0) as volcanos_count,
           coalesce(sum(pop_under_5_total), 0) as pop_under_5_total,
           coalesce(sum(pop_over_65_total), 0) as pop_over_65_total,
           coalesce(sum(poverty_families_total), 0) as poverty_families_total,
           coalesce(sum(pop_disability_total), 0) as pop_disability_total,
           coalesce(sum(pop_not_well_eng_speak), 0) as pop_not_well_eng_speak,
           coalesce(sum(pop_without_car), 0) as pop_without_car,
           coalesce(sum(populated_area) / 1000000.0, 0) as populated_area_km2,
           coalesce(sum(man_distance_to_fire_brigade), 0) as man_distance_to_fire_brigade,
           coalesce(sum(man_distance_to_hospital), 0) as man_distance_to_hospital,
           coalesce(sum(total_road_length), 0) as total_road_length,
           coalesce(sum(view_count_bf2402), 0) as view_count_bf2402,
           coalesce(sum(eatery_count), 0) as eatery_count,
           coalesce(sum(food_shops_count), 0) as food_shops_count,
           coalesce(sum(man_distance_to_bomb_shelters), 0) as man_distance_to_bomb_shelters,
           coalesce(sum(man_distance_to_charging_stations), 0) as man_distance_to_charging_stations,
           coalesce(sum(waste_basket_coverage), 0) as waste_basket_coverage,
           coalesce(sum(solar_farms_placement_suitability), 0) as solar_farms_placement_suitability,
           coalesce(sum(stddev_accel), 0) as stddev_accel,
           coalesce(sum(avg_forest_canopy_height), 0) as avg_forest_canopy_height,
           coalesce(sum(max_forest_canopy_height), 0) as max_forest_canopy_height,
           coalesce(sum(ghs_max_building_height), 0) as ghs_max_building_height,
           coalesce(sum(ghs_avg_building_height), 0) as ghs_avg_building_height,
           coalesce(sum(max_osm_building_levels), 0) as max_osm_building_levels,
           coalesce(sum(avg_osm_building_levels), 0) as avg_osm_building_levels,
           coalesce(sum(oam_coverage_area), 0) as oam_coverage_area,
           1::float as one
    from (
             select h3, count as count, count_6_months as count_6_months, building_count as building_count,
                    building_count_6_months as building_count_6_months,  null::float as total_building_count,
                    null::float as highway_length, null::float as highway_length_6_months, osm_users as osm_users,
                    null::float as population, null::float as residential, null::float as gdp, min_ts as min_ts, max_ts as max_ts,
                    avgmax_ts as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from osm_object_count_grid_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, population as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from kontur_population_h3
             union all
             select h3, null::float as count, null::float as count_6_months,null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, gdp::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from gdp_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, local_hours as local_hours, total_hours as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel, 
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height,
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels,
                    null::float as oam_coverage_area, h3_get_resolution(h3) as resolution
             from user_hours_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel, 
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height,
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels,
                    null::float as oam_coverage_area, h3_get_resolution(h3) as resolution
             from residential_pop_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, view_count::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from tile_logs_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, building_count as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from building_count_grid_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    wildfires::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from global_fires_stat_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, confirmed as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from covid19_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    population as population_prev, null::float as industrial_area, null::float as volcanos_count,
                    null::float as pop_under_5_total, null::float as pop_over_65_total, null::float as poverty_families_total,
                    null::float as pop_disability_total, null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from kontur_population_v5_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from osm_landuse_industrial_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, volcanos_count::float, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from osm_volcanos_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, pop_under_5_total,
                    pop_over_65_total, poverty_families_total, pop_disability_total, pop_not_well_eng_speak, pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from us_census_tracts_stats_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, man_distance as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from isodist_fire_stations_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, man_distance as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from isodist_hospitals_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    total_road_length as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from total_road_length_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_v2, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car, null::float as populated_area, 
                    null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from tile_logs_bf2402_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_v2, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car, null::float as populated_area, 
                    null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from osm_road_segments_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_v2, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car, null::float as populated_area, 
                    null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from osm_road_segments_6_months_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_v2, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car, null::float as populated_area,
                    null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    eatery_count::float, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from osm_places_eatery_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_v2, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car, null::float as populated_area,
                    null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, food_shops_count::float, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from osm_places_food_shops_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, man_distance as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from isodist_bomb_shelters_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    man_distance as man_distance_to_charging_stations, null::float as waste_basket_coverage, 
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from isodist_charging_stations_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, waste_basket_coverage, 
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from waste_containers_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage, 
                    solar_farms_placement_suitability, null::float as stddev_accel,  
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from solar_farms_placement_suitability_synthetic_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, stddev_accel, 
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from live_sensor_data_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage, 
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel, 
                    avg_forest_canopy_height, max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from meta_forest_canopy_height_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,                     
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    max_height as ghs_max_building_height, avg_height as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from ghs_building_height_grid_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,                     
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    max_levels as max_osm_building_levels, avg_levels as avg_osm_building_levels, 
                    null::float as oam_coverage_area, resolution
             from osm_building_levels_h3
             union all
             select h3, null::float as count, null::float as count_6_months, null::float as building_count,
                    null::float as building_count_6_months, null::float as total_building_count, null::float as highway_length,
                    null::float as highway_length_6_months, null::float as osm_users, null::float as population,
                    null::float as residential, null::float as gdp, null::float as min_ts, null::float as max_ts,
                    null::float as avgmax_ts, null::float as local_hours, null::float as total_hours, null::float as view_count,
                    null::float as wildfires, null::float as covid19_confirmed,
                    null::float as population_prev, null::float as industrial_area, null::float as volcanos_count, null::float as pop_under_5_total,
                    null::float as pop_over_65_total, null::float as poverty_families_total, null::float as pop_disability_total,
                    null::float as pop_not_well_eng_speak, null::float as pop_without_car,
                    null::float as populated_area, null::float as man_distance_to_fire_brigade, null::float as man_distance_to_hospital,
                    null::float as total_road_length, null::float as view_count_bf2402,
                    null::float as eatery_count, null::float as food_shops_count, null::float as man_distance_to_bomb_shelters,                     
                    null::float as man_distance_to_charging_stations, null::float as waste_basket_coverage,
                    null::float as solar_farms_placement_suitability, null::float as stddev_accel,
                    null::float as avg_forest_canopy_height, null::float as max_forest_canopy_height,
                    null::float as ghs_max_building_height, null::float as ghs_avg_building_height, 
                    null::float as max_osm_building_levels, null::float as avg_osm_building_levels, oam_coverage_area, resolution
             from oam_global_coverage_h3
        ) z
    group by 2, 1
);


drop table if exists stat_h3;
create table stat_h3  as (
    select a.h3,
           a.zoom,
           a.population,
           ST_Area(h3_cell_to_boundary_geography(a.h3)) / 1000000.0 as area_km2,
           a.view_count,
           a.count,
           a.one,
           a.populated_area_km2,
           a.building_count,
           a.highway_length / 1000.0 as highway_length,
           a.total_road_length / 1000.0 as total_road_length,
           a.local_hours,
           a.total_hours,
           a.resolution,
           a.avgmax_ts,
           a.man_distance_to_fire_brigade,
           a.view_count_bf2402,
           (coalesce(pf.days_mintemp_above_25c_1c, 0))::float as days_mintemp_above_25c_1c,
           a.total_building_count,
           a.count_6_months,
           a.building_count_6_months,
           a.highway_length_6_months / 1000.0 as highway_length_6_months,
           a.osm_users,
           a.residential,
           a.gdp,
           a.min_ts,
           a.max_ts,
           a.wildfires,
           a.covid19_confirmed,
           a.population_prev,
           a.industrial_area,
           a.volcanos_count,
           a.pop_under_5_total,
           a.pop_over_65_total,
           a.poverty_families_total,
           a.pop_disability_total,
           a.pop_not_well_eng_speak,
           a.pop_without_car,
           a.man_distance_to_hospital,
           a.man_distance_to_bomb_shelters,
           a.man_distance_to_charging_stations,
           a.eatery_count,
           a.food_shops_count,
           (ST_Area(h3_cell_to_boundary_geography(a.h3)) / 1000000.0) * a.waste_basket_coverage / (49.0 * POWER(7, 8 - a.resolution)) as waste_basket_coverage_area_km2,
           a.solar_farms_placement_suitability,
           a.stddev_accel,
           a.avg_forest_canopy_height,
           a.max_forest_canopy_height,
           a.ghs_max_building_height, 
           a.ghs_avg_building_height,
           a.max_osm_building_levels,
           a.avg_osm_building_levels,
           a.oam_coverage_area,
           (coalesce(ms.mapswipe_area, 0))::float as mapswipe_area_km2,
           (coalesce(gbc.avg_slope_gebco_2022, 0))::float as avg_slope_gebco_2022,
           (coalesce(gbc.avg_elevation_gebco_2022, 0))::float as avg_elevation_gebco_2022,
           (coalesce(cf.forest_area, 0))::float as forest,
           (coalesce(cf.evergreen_needle_leaved_forest, 0))::float as evergreen_needle_leaved_forest,
           (coalesce(cf.shrubs, 0))::float as shrubs,
           (coalesce(cf.herbage, 0))::float as herbage,
           (coalesce(cf.unknown_forest, 0))::float as unknown_forest,
           (coalesce(cf.cropland, 0))::float as cropland,
           (coalesce(cf.wetland, 0))::float as wetland,
           (coalesce(cf.moss_lichen, 0))::float as moss_lichen,
           (coalesce(cf.bare_vegetation, 0))::float as bare_vegetation,
           (coalesce(cf.builtup, 0))::float as builtup,
           (coalesce(cf.snow_ice, 0))::float as snow_ice,
           (coalesce(cf.permanent_water, 0))::float as permanent_water,
           (coalesce(nd.avg_ndvi, 0))::float as avg_ndvi,
           (coalesce(pf.days_maxtemp_over_32c_1c, 0))::float as days_maxtemp_over_32c_1c,
           (coalesce(pf.days_maxtemp_over_32c_2c, 0))::float as days_maxtemp_over_32c_2c,
           (coalesce(pf.days_mintemp_above_25c_2c, 0))::float as days_mintemp_above_25c_2c,
           (coalesce(pf.days_maxwetbulb_over_32c_1c, 0))::float as days_maxwetbulb_over_32c_1c,
           (coalesce(pf.days_maxwetbulb_over_32c_2c, 0))::float as days_maxwetbulb_over_32c_2c,
           (coalesce(pf.mandays_maxtemp_over_32c_1c, 0))::float as mandays_maxtemp_over_32c_1c,
           (coalesce(disaster_event_episodes_h3.hazardous_days_count, 0))::float as hazardous_days_count,
           (coalesce(disaster_event_episodes_h3.earthquake_days_count, 0))::float as earthquake_days_count,
           (coalesce(disaster_event_episodes_h3.wildfire_days_count, 0))::float as wildfire_days_count,
           (coalesce(disaster_event_episodes_h3.drought_days_count, 0))::float as drought_days_count,
           (coalesce(disaster_event_episodes_h3.cyclone_days_count, 0))::float as cyclone_days_count,
           (coalesce(disaster_event_episodes_h3.volcano_days_count, 0))::float as volcano_days_count,
           (coalesce(disaster_event_episodes_h3.flood_days_count, 0))::float as flood_days_count,
           (coalesce(facebook_medium_voltage_distribution_h3.powerlines, 0))::float as powerlines,
           (coalesce(nl.intensity, 0))::float as night_lights_intensity,
           (coalesce(gsa.gsa_ghi, 0))::float as gsa_ghi,
           (coalesce(wc_temp.worldclim_avg_temperature, 0))::float as worldclim_avg_temperature,
           (coalesce(wc_temp.worldclim_min_temperature, 0))::float as worldclim_min_temperature,
           (coalesce(wc_temp.worldclim_max_temperature, 0))::float as worldclim_max_temperature,
           (coalesce(wc_temp.worldclim_amp_temperature, 0))::float as worldclim_amp_temperature,
           (coalesce(prox.powerlines_proximity_m, 0))::float as powerlines_proximity_m,
           (coalesce(prox.populated_areas_proximity_m, 0))::float as populated_areas_proximity_m,
           (coalesce(prox.power_substations_proximity_m, 0))::float as power_substations_proximity_m,
           (coalesce(solar_panels.solar_power_plants, 0))::float as solar_power_plants,
           (coalesce(sfty.safety_index, 0))::float as safety_index,
           (coalesce(wtr.t2019, 0))::float as worldbank_total_tax_2019,
           (coalesce(wng.years_to_naturalisation, 0))::float as years_to_naturalisation,
           (coalesce(wng.multiple_citizenship, 0))::float as multiple_citizenship,
           (coalesce(osmht.osm_hotels_count, 0))::float as osm_hotels_count,
           (coalesce(osmht.max_osm_hotels_assesment, 0))::float as max_osm_hotels_assesment,
           (coalesce(osmht.avg_osm_hotels_assesment, 0))::float as avg_osm_hotels_assesment,
           (coalesce(osm_culture_venues_h3.osm_historical_sites_and_museums_count, 0))::float as osm_historical_sites_and_museums_count,
           (coalesce(osm_culture_venues_h3.osm_art_venues_count, 0))::float as osm_art_venues_count,
           (coalesce(osm_culture_venues_h3.osm_entertainment_venues_count, 0))::float as osm_entertainment_venues_count,
           (coalesce(osm_culture_venues_h3.osm_cultural_and_comunity_centers_count, 0))::float as osm_cultural_and_comunity_centers_count,
           (coalesce(oam_number_of_pixels_h3.oam_number_of_pixels, 0))::float as oam_number_of_pixels,
           (coalesce(worldbank_inflation_h3.inflation, 0))::float as worldbank_inflation,
           (coalesce(osm_pharmacy_h3.osm_pharmacy_count, 0))::float as osm_pharmacy_count,
           (coalesce(idmc_country_2023_h3.conflict_stock_displacement, 0))::float as conflict_stock_displacement,
           (coalesce(idmc_country_2023_h3.disaster_stock_displacement, 0))::float as disaster_stock_displacement,
           (coalesce(idmc_country_2023_h3.conflict_internal_displacements, 0))::float as conflict_internal_displacements,
           (coalesce(idmc_country_2023_h3.disaster_internal_displacements, 0))::float as disaster_internal_displacements,
           ST_Transform(h3_cell_to_boundary_geometry(a.h3), 3857) as geom
    from stat_h3_in           a
         left join gebco_2022_h3 gbc on (a.h3 = gbc.h3)
         left join copernicus_landcover_h3 cf on (a.h3 = cf.h3)
         left join pf_maxtemp_h3 pf on (a.h3 = pf.h3)
         left join ndvi_2019_06_10_h3 nd on (a.h3 = nd.h3)
         left join disaster_event_episodes_h3 on (a.h3 = disaster_event_episodes_h3.h3)
         left join facebook_medium_voltage_distribution_h3 on (a.h3 = facebook_medium_voltage_distribution_h3.h3)
         left join night_lights_h3 nl on (a.h3 = nl.h3)
         left join global_solar_atlas_h3 gsa on (a.h3 = gsa.h3)
         left join worldclim_temperatures_h3 wc_temp on (a.h3 = wc_temp.h3)
         left join mapswipe_hot_tasking_data_h3 ms on (a.h3 = ms.h3)
         left join proximities_h3 prox on (a.h3 = prox.h3)
         left join existing_solar_power_panels_h3 solar_panels on (a.h3 = solar_panels.h3)
         left join safety_index_h3 sfty on (a.h3 = sfty.h3)
         left join worldbank_tax_rate_h3 wtr on (a.h3 = wtr.h3)
         left join wikidata_naturalization_gap_h3 wng on (a.h3 = wng.h3)
         left join osm_hotels_h3 osmht on (a.h3 = osmht.h3)
         left join osm_culture_venues_h3 on (a.h3 = osm_culture_venues_h3.h3)
         left join oam_number_of_pixels_h3 on (a.h3 = oam_number_of_pixels_h3.h3)
         left join worldbank_inflation_h3 on (a.h3 = worldbank_inflation_h3.h3)
         left join osm_pharmacy_h3 on (a.h3 = osm_pharmacy_h3.h3)
         left join idmc_country_2023_h3 on (a.h3 = idmc_country_2023_h3.h3)
);
drop table stat_h3_in;
vacuum analyze stat_h3;
create index on stat_h3 using gist (geom, zoom);
-- cannot create index with more than 32 columns, so create more indexes
create index stat_h3_brin_pt1 on stat_h3 using brin (
                                                     area_km2, populated_area_km2, population, count, building_count,
                                                     highway_length, resolution, zoom, geom, one, total_building_count,
                                                     max_ts, total_hours, avgmax_ts, forest,
                                                     evergreen_needle_leaved_forest, shrubs, herbage, unknown_forest,
                                                     min_ts, residential, view_count, count_6_months, total_road_length,
                                                     view_count_bf2402, night_lights_intensity
    );

create index stat_h3_brin_pt2 on stat_h3 using brin (
                                                     gdp, highway_length_6_months, wildfires, avg_ndvi,building_count_6_months,
                                                     local_hours, osm_users, covid19_confirmed, population_prev,
                                                     industrial_area, volcanos_count, pop_under_5_total,
                                                     pop_over_65_total, poverty_families_total, pop_disability_total,
                                                     pop_not_well_eng_speak, pop_without_car, mandays_maxtemp_over_32c_1c,
                                                     days_maxtemp_over_32c_1c, days_maxtemp_over_32c_2c,
                                                     days_mintemp_above_25c_1c, days_mintemp_above_25c_2c,
                                                     days_maxwetbulb_over_32c_1c, days_maxwetbulb_over_32c_2c,
                                                     man_distance_to_fire_brigade, man_distance_to_hospital,
                                                     flood_days_count, powerlines
    );

create index stat_h3_brin_pt3 on stat_h3 using brin (
                                                     eatery_count, food_shops_count, avg_elevation_gebco_2022,
                                                     avg_slope_gebco_2022, mapswipe_area_km2, gsa_ghi,
                                                     worldclim_avg_temperature, worldclim_min_temperature,
                                                     worldclim_max_temperature, worldclim_amp_temperature,
                                                     man_distance_to_bomb_shelters, man_distance_to_charging_stations,
                                                     powerlines_proximity_m, waste_basket_coverage_area_km2,
                                                     populated_areas_proximity_m, power_substations_proximity_m,
                                                     solar_farms_placement_suitability, solar_power_plants,
                                                     safety_index, cropland, wetland, moss_lichen, bare_vegetation,
                                                     builtup, snow_ice, permanent_water, avg_forest_canopy_height,
                                                     max_forest_canopy_height, worldbank_total_tax_2019,
                                                     years_to_naturalisation, multiple_citizenship
    );

create index stat_h3_brin_pt4 on stat_h3 using brin (
                                                     stddev_accel, ghs_max_building_height, ghs_avg_building_height,
                                                     max_osm_building_levels, avg_osm_building_levels, osm_hotels_count,
                                                     max_osm_hotels_assesment, avg_osm_hotels_assesment, oam_coverage_area,
                                                     osm_historical_sites_and_museums_count, osm_art_venues_count,
                                                     osm_entertainment_venues_count, osm_cultural_and_comunity_centers_count,
                                                     oam_number_of_pixels, worldbank_inflation, osm_pharmacy_count,
                                                     conflict_stock_displacement, disaster_stock_displacement,
                                                     conflict_internal_displacements, disaster_internal_displacements
    );