select ST_AsMVT(q, 'stats', 8192, 'geom')
from
    (
        select
            count,
            count_6_months,
            building_count,
            building_count_6_months,
            highway_length,
            highway_length_6_months,
            osm_users,
            population,
            gdp,
            coalesce(min_ts, 0) as min_ts,
            coalesce(max_ts, 0) as max_ts,
            coalesce(avgmax_ts, 0) as avgmax_ts,
            area_km2,
            populated_area_km2,
            local_hours,
            total_hours,
            view_count,
            one,
            total_building_count,
            wildfires,
            covid19_vaccines,
            avg_slope,
            avg_slope_gebco_2022,
            forest,
            avg_ndvi,
            covid19_confirmed,
            population_prev,
            industrial_area,
            volcanos_count,
            pop_under_5_total,
            pop_over_65_total,
            poverty_families_total,
            pop_disability_total,
            pop_not_well_eng_speak,
            pop_without_car,
            evergreen_needle_leaved_forest,
            shrubs,
            herbage,
            unknown_forest,
            avg_elevation,
            avg_elevation_gebco_2022,
            days_maxtemp_over_32c_1c,
            days_maxtemp_over_32c_2c,
            days_mintemp_above_25c_1c,
            days_mintemp_above_25c_2c,
            days_maxwetbulb_over_32c_1c,
            days_maxwetbulb_over_32c_2c,
            mandays_maxtemp_over_32c_1c,
            man_distance_to_fire_brigade,
            man_distance_to_hospital,
            total_road_length,
            foursquare_visits_count,
            foursquare_places_count,
            view_count_bf2402,
            mhr_index,
            mhe_index,
            resilience_index,
            coping_capacity_index,
            vulnerability_index,
            hazardous_days_count,
            earthquake_days_count,
            drought_days_count,
            cyclone_days_count,
            wildfire_days_count,
            volcano_days_count,
            flood_days_count,
            night_lights_intensity,
            mapswipe_area,
            ST_AsMVTGeom(geom, ST_TileEnvelope($1, $2, $3), 8192, 64, true) as geom
        from stat_h3
        where zoom = $1
          and geom && ST_TileEnvelope($1, $2, $3)
    ) as q;
