apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basemap-claim
spec:
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basemap-postgres-claim
spec:
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: batch/v1
kind: Job
metadata:
  name: basemap
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 604800 # week
  template:
    spec:
      containers:
      - name: basemap-rendering
        image: nexus.kontur.io:8085/konturdev/build-basemap
        imagePullPolicy: Always
        volumeMounts:
          - name: basemap-storage
            mountPath: /persisted-volume
        env:
          - name: PGHOST
            value: localhost
          - name: PGUSER
            value: gis
          - name: PGDATABASE
            value: gis
          - name: AWS_DEFAULT_REGION
            value: eu-central-1
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: kontur-aws
                key: access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: kontur-aws
                key: secret-access-key-id
      - name: postgres
        image: postgis/postgis:14-master
        args:
          - "-c"
          - "maintenance_work_mem=1GB"
          - "-c"
          - "shared_buffers=2GB"
          - "-c"
          - "effective_cache_size=128GB"
          - "-c"
          - "random_page_cost=1.1"
          - "-c"
          - "effective_io_concurrency=200"
          - "-c"
          - "work_mem=2GB"
          - "-c"
          - "max_connections=32"
          - "-c"
          - "wal_level=minimal"
          - "-c"
          - "max_wal_senders=0"
        env:
          - name: S3_BASEMAP_PATH
            valueFrom:
              configMapKeyRef:
                name: basemap-config
                key: s3-basemap-path
          - name: POSTGRES_USER
            value: gis
          - name: POSTGRES_DATABASE
            value: gis
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: basemap-postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: basemap-storage
        persistentVolumeClaim:
          claimName: basemap-claim
      - name: basemap-postgres-storage
        persistentVolumeClaim:
          claimName: basemap-postgres-claim
      restartPolicy: Never
      imagePullSecrets:
        - name: kontur-nexus
        - name: kontur-aws
