apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basemap-claim
spec:
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basemap-postgres-claim
spec:
  resources:
    requests:
      storage: 400Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: batch/v1
kind: Job
metadata:
  name: basemap
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 604800 # week
  template:
    spec:
      containers:
      - name: basemap
        image: nexus.kontur.io:8085/build-basemap
        command: ["make", "-j", "data/basemap.mbtiles"]
        volumeMounts:
          - name: basemap-storage
            mountPath: /data
        env:
          - name: PGHOST
            value: localhost
          - name: PGUSER
            value: gis
          - name: PGDATABASE
            value: gis
      - name: postgres
        image: postgis/postgis:14-master
        env:
          - name: POSTGRES_USER
            value: gis
          - name: POSTGRES_DATABASE
            value: gis
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: basemap-postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: basemap-storage
        persistentVolumeClaim:
          claimName: basemap-claim
      - name: basemap-postgres-storage
        persistentVolumeClaim:
          claimName: basemap-postgres-claim
      restartPolicy: Never
      imagePullSecrets:
          - name: kontur-nexus
