{'bwa': {'customviz':[{'url': 'https://studio.foursquare.com/public/5c653399-e79c-4aee-9891-df378da2dd43'}]},
'swz': {'customviz':[{'url': 'https://studio.foursquare.com/public/5c653399-e79c-4aee-9891-df378da2dd43'}]},
'lso': {'customviz':[{'url': 'https://studio.foursquare.com/public/5c653399-e79c-4aee-9891-df378da2dd43'}]}
}