{'esh': {'#meta+id': '245', '#country+code+v_hrinfo_country': '427', '#country+code+v_reliefweb': '253', '#country+alt+i_ru+name+v_unterm': ''},
'rzc': {'#meta+id': '245', '#country+code+v_hrinfo_country': '427', '#country+code+v_reliefweb': '253', '#country+alt+i_ru+name+v_unterm': ''},
'irg': {'#meta+id': '245', '#country+code+v_hrinfo_country': '427', '#country+code+v_reliefweb': '253', '#country+alt+i_ru+name+v_unterm': ''}
}